### ISSUE TITLE
Heroku Support

### ISSUE THREAD

**Issue by UsamaKarim** [tgbot-collection/ytdl-bot#6]
Hi, I checked a lot of bots that are not working for Dailymotion but only yours is working. Can you please make it possible to deploy to Heroku? As I know nothing python so it's not possible for me to add Heroku support. I don't want to abuse the bot hosted by yourself 😅

**Comment by BennyThink** [comment]
Check it here?

https://devcenter.heroku.com/articles/getting-started-with-python

**Comment by UsamaKarim** [comment]
How about a deployable button in your repo?

**Comment by BennyThink** [comment]
Do you have any example for this button? It would be better if there's any hints or tutorials.

**Comment by UsamaKarim** [comment]
Check this repo
[https://github.com/ysfchn/SamFetch](https://github.com/ysfchn/SamFetch)

**Comment by BennyThink** [comment]
![image](https://user-images.githubusercontent.com/14024832/119285920-c2c7c680-bc75-11eb-89f6-861f9f1362ed.png)


It's working now - please apply your own app_id and app_hash at https://my.telegram.org/apps and deploy to heroku.
